### ISSUE TITLE
Hello there

### ISSUE THREAD

**Issue by agarzon** [Tonyx97/DX12-Base--DXTK-#1]
Hello, hola :smile:

Not sure if I should try with english or spanish, anyway here my question:

This is the base of the "internal" bf 1 published in unknownc.... ? :relaxed:

Anyways, great thing. Tried yesterday and it makes the job pretty well. Gracias. :+1:

**Comment by Tonyx97** [comment]
Sorry for late answer I don't use to answer in GitHub, but I'm more active now. Anwering your question (you may answered yourself by now): no it's not the base, this is DX12 and BF1 uses DX11 (also DX12 but why use dx12 when u can use dx11 for hacks). And you're welcome :)

**Comment by navaneeth-dev** [comment]
What was the d3d11 renderer? Thanks :)
